"""Shared hardware / imaging constants for main and GUI."""

IMAGING_ROWS = 8
IMAGING_COLS = 8
CAMERA_STEPSIZE = 95
PETRI_STEPSIZE = 76

PETRI_DISH_PRE_UP = 740
CAMERA_DISH_PRE_UP = 3730
PETRI_DISH_PRE_UP_ROW2 = 1460
CAMERA_DISH_PRE_UP_ROW2 = 3750

PETRI_TRAY_ROWS = 2
PETRI_TRAY_COLS = 5
MAX_PETRI_DISHES = PETRI_TRAY_ROWS * PETRI_TRAY_COLS

# Incubation GUI
INCUBATION_TEMP_OPTIONS = (30, 37, 44)
DEFAULT_INCUBATION_TEMP_C = 37
DEFAULT_INCUBATION_MINUTES = 1.0
DEFAULT_INCUBATION_COUNT = 3
INCUBATION_MIN_STEP = 0.5
INCUBATION_MIN_MIN = 0.5
INCUBATION_MIN_MAX = 600.0

# Five picture time-points (minutes before each capture in timed study)
NUM_PICTURE_SLOTS = 5
PICTURE_TIME_PRESETS = (1, 3, 5, 10, 15, 30)
DEFAULT_PICTURE_TIMES = (3, 3, 3, 3, 3)
