"""Shared hardware / imaging constants for main and GUI."""

IMAGING_ROWS = 8
IMAGING_COLS = 8
CAMERA_STEPSIZE = 95
PETRI_STEPSIZE = 76

PETRI_DISH_PRE_UP = 740
CAMERA_DISH_PRE_UP = 3730
PETRI_DISH_PRE_UP_ROW2 = 1460
CAMERA_DISH_PRE_UP_ROW2 = 3750

PETRI_TRAY_ROWS = 2
PETRI_TRAY_COLS = 5
MAX_PETRI_DISHES = PETRI_TRAY_ROWS * PETRI_TRAY_COLS

# Default incubation (GUI overridable)
DEFAULT_INCUBATION_TEMP_C = 37.0
DEFAULT_INCUBATION_MINUTES = 1.0
DEFAULT_INCUBATION_COUNT = 3

# Six selectable intervals (minutes) before each picture round; default 3 each
PICTURE_INTERVAL_OPTIONS = (1, 3, 5, 10, 15, 30)
DEFAULT_PICTURE_INTERVAL_MIN = 3
DEFAULT_PICTURE_ROUNDS = 1
MAX_PICTURE_ROUNDS = 6
